apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: observability-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
      containers:
        - name: grafana
          image: grafana/grafana:13.0.8
          ports:
            - name: web
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /api/health
              port: web
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: data
              mountPath: /var/lib/grafana
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: observability-lab
spec:
  selector:
    app: grafana
  ports:
    - name: web
      port: 3000
      targetPort: web
