apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
  namespace: observability-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
      containers:
        - name: pushgateway
          image: prom/pushgateway:v1.11.3
          ports:
            - name: push
              containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: observability-lab
spec:
  selector:
    app: pushgateway
  ports:
    - name: push
      port: 9091
      targetPort: push
